[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
	" Ctrl+nでファイルツリーを表示/非表示する
	nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=35<CR>
'''

# /----- ddc.vim ------
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_source = '''
	call ddc#custom#patch_global('sources', ['around'])
	call ddc#custom#patch_global('sourceOptions', {
		\ '_': {
		\   'matchers': ['matcher_head'],
		\   'sorters': ['sorter_rank']
		\ },
		\ 'around': {
		\   'mark': 'around'
		\ },
		\ 'nvim-lsp': {
		\   'mark': 'lsp',
		\   'forceCompletionPattern': '\.\w*|:\w*|->\w*'},
		\ })
	call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

# ------ ddc.vim -----/

# / --------- dein/lazy.toml ---------
[[plugins]]
 repo = 'neovim/nvim-lspconfig'

[[plugins]]
 repo = 'williamboman/mason.nvim'

[[plugins]]
 repo = 'williamboman/mason-lspconfig.nvim'

[[plugins]]
 repo = 'hrsh7th/nvim-cmp'
 
[[plugins]]
 repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
 repo = 'hrsh7th/vim-vsnip'

# --------- dein/lazy.toml --------- /
