[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
	" Ctrl+nでファイルツリーを表示/非表示する
	nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

# /----- ddc.vim ------
[[plugins]]
repo = 'Shougo/ddc.vim'
hook = '''
	" Set a single option
	call ddc#custom#patch_global('ui', 'native')

	" Pass a dictionary to set multiple options
	call ddc#custom#patch_global(#{
	\   sourceOptions: #{
	\     _: #{
	\       keywordPattern: '[a-zA-Z_]\w*',
	\     },
	\   },
	\   smartCase: v:true,
	\ })

	call ddc#custom#patch_filetype(['c', 'cpp'], 'sources', ['around'])
	" <TAB>: completion.
	inoremap <silent><expr> <TAB>
	\ pumvisible() ? '<C-n>' :
	\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
	\ '<TAB>' : ddc#map#manual_complete()

	" <S-TAB>: completion back.
	inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

	call ddc#enable()
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
# ------ ddc.vim -----/
